name: .NET

on:
  push:
    branches: 
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      is_release:
        description: Should this be a release
        required: true
        default: 'false'
        
jobs:
  build-test-push-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    #- name: Test
    #  run: dotnet test -c Release --no-restore --verbosity normal    
    - name: Pack
      if: github.event.inputs.is_release == 'true'
      run: |
        dotnet pack src/AsyncFluentGenerator/AsyncFluentGenerator.csproj -c Release --include-source -o out
    - name: Push
      if: ${{ success() && github.ref == 'refs/heads/main' && github.event.inputs.is_release == 'true' }}
      run: |
        dotnet nuget push 'out/*.nupkg' -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
        
        
        
